mqtt:
  host: 'mqtt-broker.local'
  port: 1883
  username: 'mqtt-user'
  password: ''
  topic_prefix: 'yamaha-rxv1800'
  client_id: 'rxv1800-mqtt'
  discovery:
    topic_prefix: 'homeassistant'
    unique_id: 'yamaha-rxv1800'
    #via_device_id: ''

serial:
  device: '/dev/ttyUSB0'

limits:
  volume: -20  # or None

logging:
  incremental: true
  root:
    level: INFO
